import { createEntityConfig, normalizeProject } from "./model.js";

export const INTERACTION_DEMO_DURATION = 10;

const environment = (overrides = {}) => createEntityConfig("environment", {
  state: "固定碰撞边界",
  ...overrides,
});

const character = (state) => createEntityConfig("character", {
  state,
  physics: { bodyType: "kinematic", mass: 68, friction: 0.72, restitution: 0 },
});

const prop = (state) => createEntityConfig("prop", {
  state,
  physics: { bodyType: "kinematic", mass: 0.45, friction: 0.56, restitution: 0.05 },
});

const actorObjects = ({ id, name, position, rotation, color, accent }) => [
  {
    id,
    type: "group",
    name,
    position,
    rotation,
    dimensions: [1, 1, 1],
    entity: character("等待指令"),
    motion: { kind: "wheel", leanDegrees: 3, bankDegrees: 2 },
    asset: {
      nodes: { root: id, head: `${id}-head`, arm: `${id}-arm`, effector: `${id}-hand`, statusLight: `${id}-status` },
      animations: { idle: "idle", move: "move", interact: "interact", react: "react" },
    },
    interactionSpec: {
      anchors: {
        gaze: [0, 1.46, -0.18],
        shoulder: [0, 1.02, -0.12],
        effector: [0, 1.02, -0.72],
        carry: [0, 0.98, -0.62],
      },
    },
  },
  {
    id: `${id}-body`,
    parentId: id,
    nodeRole: "body",
    type: "box",
    name: `${name} · 机身`,
    position: [0, 0.84, 0],
    dimensions: [0.72, 0.86, 0.52],
    color,
    render: { roughness: 0.42, metalness: 0.46, emissive: color, emissiveIntensity: 0.06 },
    entity: character("角色子节点"),
  },
  {
    id: `${id}-head`,
    parentId: id,
    nodeRole: "head",
    type: "sphere",
    name: `${name} · 观察头`,
    position: [0, 1.48, -0.05],
    dimensions: [0.52, 0.38, 0.46],
    color: accent,
    render: { roughness: 0.32, metalness: 0.58, emissive: accent, emissiveIntensity: 0.08 },
    entity: character("角色子节点"),
  },
  {
    id: `${id}-arm`,
    parentId: id,
    nodeRole: "arm",
    type: "box",
    name: `${name} · 伸缩机械臂`,
    position: [0, 1.02, -0.4],
    dimensions: [0.13, 0.13, 0.56],
    color: accent,
    render: { roughness: 0.3, metalness: 0.62, emissive: accent, emissiveIntensity: 0.08 },
    entity: character("角色子节点"),
  },
  {
    id: `${id}-hand`,
    parentId: id,
    nodeRole: "effector",
    type: "sphere",
    name: `${name} · 交互执行器`,
    position: [0, 1.02, -0.68],
    dimensions: [0.24, 0.24, 0.24],
    color: "#f2a33a",
    render: { roughness: 0.25, metalness: 0.65, emissive: "#f2a33a", emissiveIntensity: 0.22 },
    entity: character("接触执行器"),
  },
  {
    id: `${id}-wheel`,
    parentId: id,
    nodeRole: "locomotion",
    type: "cylinder",
    name: `${name} · 移动轮`,
    position: [0, 0.28, 0.08],
    rotation: [90, 0, 0],
    dimensions: [0.62, 0.28, 0.62],
    color: "#252b2c",
    render: { roughness: 0.72, metalness: 0.38 },
    entity: character("角色子节点"),
  },
  {
    id: `${id}-status`,
    parentId: id,
    nodeRole: "statusLight",
    type: "sphere",
    name: `${name} · 状态灯`,
    position: [0, 1.52, -0.28],
    dimensions: [0.13, 0.13, 0.13],
    color: accent,
    render: {
      roughness: 0.2,
      metalness: 0.1,
      emissive: accent,
      emissiveIntensity: 1.8,
      light: { color: accent, intensity: 0.6, distance: 2.4, decay: 2 },
    },
    entity: character("角色子节点"),
  },
];

export function createInteractionDemoProject() {
  const actorA = actorObjects({
    id: "interaction-actor-a",
    name: "角色 A · 递交者",
    position: [-4, 0, 0.8],
    rotation: [0, -65, 0],
    color: "#3d7880",
    accent: "#75d7d8",
  });
  const actorB = actorObjects({
    id: "interaction-actor-b",
    name: "角色 B · 接收者",
    position: [2.2, 0, 0],
    rotation: [0, 90, 0],
    color: "#8b6b38",
    accent: "#f0bc58",
  });

  const screenplay = `# 固定 60Hz 的十秒交互验收
镜头聚焦 交互杯，用时 0.2 秒
角色 A · 递交者 移动到 (-1.25, 0, 0)，用时 2.2 秒
角色 A · 递交者 拿起 交互杯，用时 1.2 秒
角色 A · 递交者 移动到 (1, 0, 0)，用时 1.85 秒
角色 A · 递交者 将 交互杯 交给 角色 B · 接收者，用时 1.3 秒
角色 B · 接收者 移动到 (3.25, 0, 0)，用时 1.55 秒
角色 B · 接收者 将 交互杯 放到 放置台，用时 1.25 秒
等待 0.2 秒`;

  return normalizeProject({
    id: "interaction-simulation-lab",
    name: "十秒交互仿真实验室",
    stage: "behavior",
    updatedAt: "2026-08-22T00:00:00.000Z",
    objects: [
      {
        id: "interaction-floor",
        type: "plane",
        name: "仿真地面",
        position: [0, -0.1, 0],
        dimensions: [13, 0.2, 7],
        color: "#303837",
        locked: true,
        render: { roughness: 0.94, metalness: 0.02 },
        entity: environment(),
      },
      {
        id: "interaction-backdrop",
        type: "box",
        name: "仿真背景墙",
        position: [0, 2.25, -3.15],
        dimensions: [13, 4.5, 0.22],
        color: "#202728",
        locked: true,
        render: { roughness: 0.88, metalness: 0.04 },
        entity: environment(),
      },
      {
        id: "interaction-source-table",
        type: "box",
        name: "起始台",
        position: [-0.35, 0.45, 0],
        dimensions: [1.2, 0.9, 1.2],
        color: "#6c6253",
        render: { roughness: 0.74, metalness: 0.12 },
        entity: environment(),
        interactionSpec: { anchors: { surface: [0, 0.45, 0] } },
      },
      {
        id: "interaction-destination-table",
        type: "box",
        name: "放置台",
        position: [4.15, 0.55, 0],
        dimensions: [1.35, 1.1, 1.35],
        color: "#5e6657",
        render: { roughness: 0.7, metalness: 0.16, emissive: "#4f6c55", emissiveIntensity: 0.08 },
        entity: environment(),
        interactionSpec: { anchors: { surface: [0, 0.55, 0] } },
      },
      {
        id: "interaction-cup",
        type: "cylinder",
        name: "交互杯",
        position: [-0.35, 1.18, 0],
        dimensions: [0.42, 0.56, 0.42],
        color: "#d8d0bd",
        render: { roughness: 0.36, metalness: 0.22, emissive: "#ecb454", emissiveIntensity: 0.09 },
        entity: prop("位于起始台"),
        interactionSpec: {
          anchors: { grip: [0, 0, 0], bottom: [0, -0.28, 0] },
          affordances: {
            pickup: {
              action: "pick_up",
              targetAnchor: "grip",
              actorNode: "effector",
              maxDistance: 1.1,
              resultingState: "由角色 A 持有",
              ownershipMode: "claim",
              holderAnchor: "carry",
              itemAnchor: "grip",
            },
            handoff: {
              action: "hand_over",
              targetAnchor: "grip",
              actorNode: "effector",
              maxDistance: 1.2,
              resultingState: "由角色 B 持有",
              ownershipMode: "transfer",
              recipientAnchor: "carry",
              itemAnchor: "grip",
            },
            place: {
              action: "place_on_surface",
              targetAnchor: "bottom",
              actorNode: "effector",
              maxDistance: 1.2,
              resultingState: "稳定放置",
              ownershipMode: "release",
              placementAnchor: "surface",
              itemAnchor: "bottom",
            },
          },
        },
      },
      ...actorA,
      ...actorB,
    ],
    director: {
      screenplay,
      timeline: {
        duration: INTERACTION_DEMO_DURATION,
        compiledScript: screenplay,
        compiledAt: "deterministic-interaction-fixture-v1",
        issues: [],
        clips: [
          {
            id: "interaction-camera",
            type: "camera",
            track: "camera",
            label: "镜头 · 连续跟随交接",
            start: 0,
            duration: 10,
            fromPosition: [-0.6, 4.4, 8.4],
            toPosition: [2.3, 3.9, 7.8],
            fromLookAt: [-1.2, 1, 0],
            toLookAt: [2.6, 1, 0],
            positionPath: [[-0.6, 4.4, 8.4], [-1.4, 4, 7.5], [0.8, 3.7, 7.1], [2.3, 3.9, 7.8]],
            lookAtPath: [[-1.2, 1, 0], [-0.35, 1.05, 0], [1.35, 1, 0], [2.6, 1, 0]],
            fromFov: 43,
            toFov: 40,
            motion: { easing: "minimumJerk" },
          },
          {
            id: "interaction-a-approach",
            type: "move",
            track: "character",
            label: "角色 A · 接近",
            start: 0.2,
            duration: 2.2,
            targetId: "interaction-actor-a",
            from: [-4, 0, 0.8],
            to: [-1.25, 0, 0],
            path: [[-4, 0, 0.8], [-2.8, 0, 1.15], [-1.9, 0, 0.65], [-1.25, 0, 0]],
            fromYaw: -65,
            toYaw: -90,
            motion: { easing: "minimumJerk", orientToPath: true, leanDegrees: 2.2, bankDegrees: 1.8, turnPortion: 0.28 },
          },
          {
            id: "interaction-pickup",
            type: "interaction",
            track: "character",
            label: "角色 A · 对齐并抓取",
            start: 2.35,
            duration: 1.2,
            targetId: "interaction-cup",
            secondaryTargetId: "interaction-actor-a",
            action: "pick_up",
            targetAnchor: "grip",
            actorNode: "effector",
            resultingState: "由角色 A 持有",
            ownershipMode: "claim",
            holderAnchor: "carry",
            itemAnchor: "grip",
            motion: { easing: "minimumJerk" },
          },
          {
            id: "interaction-a-carry",
            type: "move",
            track: "character",
            label: "角色 A · 连续携带",
            start: 3.5,
            duration: 1.85,
            targetId: "interaction-actor-a",
            from: [-1.25, 0, 0],
            to: [1, 0, 0],
            path: [[-1.25, 0, 0], [-0.45, 0, 0.42], [0.35, 0, 0.35], [1, 0, 0]],
            fromYaw: -90,
            toYaw: -90,
            motion: { easing: "minimumJerk", orientToPath: true, leanDegrees: 1.8, bankDegrees: 1.2, turnPortion: 0.2 },
          },
          {
            id: "interaction-handoff",
            type: "interaction",
            track: "character",
            label: "角色 A → 角色 B · 接触交接",
            start: 5.25,
            duration: 1.3,
            targetId: "interaction-cup",
            secondaryTargetId: "interaction-actor-a",
            recipientId: "interaction-actor-b",
            action: "hand_over",
            targetAnchor: "grip",
            actorNode: "effector",
            resultingState: "由角色 B 持有",
            ownershipMode: "transfer",
            recipientAnchor: "carry",
            itemAnchor: "grip",
            motion: { easing: "minimumJerk" },
          },
          {
            id: "interaction-a-clear",
            type: "move",
            track: "character",
            label: "角色 A · 让出路径",
            start: 6.5,
            duration: 1.25,
            targetId: "interaction-actor-a",
            from: [1, 0, 0],
            to: [0.35, 0, 1],
            path: [[1, 0, 0], [0.85, 0, 0.5], [0.35, 0, 1]],
            fromYaw: -90,
            toYaw: 145,
            motion: { easing: "minimumJerk", orientToPath: true, leanDegrees: 1.4, bankDegrees: 1, turnPortion: 0.35 },
          },
          {
            id: "interaction-b-carry",
            type: "move",
            track: "character",
            label: "角色 B · 携带至放置台",
            start: 6.5,
            duration: 1.55,
            targetId: "interaction-actor-b",
            from: [2.2, 0, 0],
            to: [3.25, 0, 0],
            path: [[2.2, 0, 0], [2.55, 0, 0.35], [2.95, 0, 0.28], [3.25, 0, 0]],
            fromYaw: 90,
            toYaw: -90,
            motion: { easing: "minimumJerk", orientToPath: true, leanDegrees: 1.5, bankDegrees: 1, turnPortion: 0.42 },
          },
          {
            id: "interaction-place",
            type: "interaction",
            track: "character",
            label: "角色 B · 接触并稳定放置",
            start: 8,
            duration: 1.25,
            targetId: "interaction-cup",
            secondaryTargetId: "interaction-actor-b",
            placementTargetId: "interaction-destination-table",
            action: "place_on_surface",
            targetAnchor: "bottom",
            actorNode: "effector",
            resultingState: "稳定放置",
            ownershipMode: "release",
            placementAnchor: "surface",
            itemAnchor: "bottom",
            motion: { easing: "minimumJerk" },
          },
          {
            id: "interaction-b-recover",
            type: "rotate",
            track: "character",
            label: "角色 B · 恢复朝向",
            start: 9.2,
            duration: 0.55,
            targetId: "interaction-actor-b",
            from: [0, -90, 0],
            to: [0, -70, 0],
            motion: { easing: "minimumJerk" },
          },
        ],
      },
    },
  });
}
